FROM node:14.18.2 as build-stage
WORKDIR /source
COPY . .
RUN npm install
RUN cd client
RUN npm install
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build-stage /source/build/ /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
